---

language: python

python:
  - "2.7"
  - "3.5"

install:
  - "pip install pytest-cov"

script:
  - pytest --cov=characterentities --cov-report=term --cov-report=xml --cov-branch

after_success:
  - "bash <(curl -s https://codecov.io/bash)"

cache:
  pip: true

...
